### ISSUE TITLE
Roadmap to first release

### ISSUE THREAD

**Issue by gutenye** [gutenye/react-mc#1]
- [ ] Package each component into individual package
- [x] Create documentation website
- [x] Add basic tests

## Future
- [x] Add Meta Component
